# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-30 16:59:59
"""
import arcpy

def BFE():  # BFE

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    SRCFloodVulnerability_gdb = "G:\\My Drive\\Projects\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb"
    fishnet_clip_mod1 = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\fishnet_clip_mod1"
    fishnet_clip = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\fishnet_clip"
    bfe = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\bfe"
    SRCFloodVulnerability_gdb_2_ = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb"

    # Process: Tabulate Intersection (Tabulate Intersection) 
    bfe_fn_intersect = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\bfe_fn_intersect"
    arcpy.TabulateIntersection_analysis(in_zone_features=fishnet_clip, zone_fields=["OBJECTID"], in_class_features=bfe, out_table=bfe_fn_intersect, class_fields=["bfe_bool"], sum_fields=["bfe_bool"], xy_tolerance="", out_units="UNKNOWN")

    # Process: Add Field (3) (Add Field) 
    bfe_fn_intersect_2_ = arcpy.AddField_management(in_table=bfe_fn_intersect, field_name="bfe_wgt", field_type="SHORT", field_precision=None, field_scale=None, field_length=None, field_alias="bfe_wgt", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) 
    bfe_fn_intersect_3_ = arcpy.CalculateField_management(in_table=bfe_fn_intersect_2_, field="bfe_wgt", expression="calc_wgts(!PERCENTAGE!)", expression_type="PYTHON3", code_block="def calc_wgts (pct):
    rank_val = 0
    if (pct < 20): 
            rank_val = 1
    if (pct > 20) & (pct < 40): 
            rank_val = 2
    if (pct > 40) & (pct < 60): 
            rank_val = 3
    if (pct > 60) & (pct < 80): 
            rank_val = 4
    if (pct > 80): 
            rank_val = 5
    return rank_val", field_type="TEXT")[0]

    # Process: Add Join (Add Join) 
    fishnet_clip_Layer1 = arcpy.AddJoin_management(in_layer_or_view=fishnet_clip_mod1, in_field="OBJECTID", join_table=bfe_fn_intersect_3_, join_field="OBJECTID_1", join_type="KEEP_ALL")[0]

    # Process: Feature Class to Feature Class (Feature Class to Feature Class) 
    fishnet_clip_mod2 = arcpy.FeatureClassToFeatureClass_conversion(in_features=fishnet_clip_Layer1, out_path=SRCFloodVulnerability_gdb_2_, out_name="fishnet_clip_mod2", where_clause="", field_mapping="IN_FID \"IN_FID\" true true false 4 Long 0 0,First,#,fishnet_clip_mod1_Layer,fishnet_clip_mod1.IN_FID,-1,-1;FREQUENCY \"FREQUENCY\" true true false 4 Long 0 0,First,#,fishnet_clip_mod1_Layer,fishnet_clip_mod1.FREQUENCY,-1,-1;SUM_IN_FID \"SUM_IN_FID\" true true false 8 Double 0 0,First,#,fishnet_clip_mod1_Layer,fishnet_clip_mod1.SUM_IN_FID,-1,-1;rls_wgt \"rls_wgt\" true true false 2 Short 0 0,First,#,fishnet_clip_mod1_Layer,fishnet_clip_mod1.rls_wgt,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,fishnet_clip_mod1_Layer,fishnet_clip_mod1.Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,fishnet_clip_mod1_Layer,fishnet_clip_mod1.Shape_Area,-1,-1;OBJECTID \"OBJECTID\" false true false 4 Long 0 9,First,#,fishnet_clip_mod1_Layer,bfe_fn_intersect.OBJECTID,-1,-1;OBJECTID_1 \"OID\" true true false 4 Long 0 0,First,#,fishnet_clip_mod1_Layer,bfe_fn_intersect.OBJECTID_1,-1,-1;bfe_bool \"bfe_bool\" true true false 2 Short 0 0,First,#,fishnet_clip_mod1_Layer,bfe_fn_intersect.bfe_bool,-1,-1;bfe_bool_1 \"bfe_bool\" true true false 2 Short 0 0,First,#,fishnet_clip_mod1_Layer,bfe_fn_intersect.bfe_bool_1,-1,-1;AREA \"AREA\" true true false 8 Double 0 0,First,#,fishnet_clip_mod1_Layer,bfe_fn_intersect.AREA,-1,-1;PERCENTAGE \"PERCENTAGE\" true true false 8 Double 0 0,First,#,fishnet_clip_mod1_Layer,bfe_fn_intersect.PERCENTAGE,-1,-1;bfe_wgt \"bfe_wgt\" true true false 2 Short 0 0,First,#,fishnet_clip_mod1_Layer,bfe_fn_intersect.bfe_wgt,-1,-1", config_keyword="")[0]

    # Process: Calculate Field (2) (Calculate Field) 
    fishnet_clip_mod2_2_ = arcpy.CalculateField_management(in_table=fishnet_clip_mod2, field="bfe_wgt", expression="zero_out(!bfe_wgt!)", expression_type="PYTHON3", code_block="def zero_out(flswgt):
    if flswgt is not None:
        return flswgt
    else:
        return 0", field_type="TEXT")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"D:\SRCFloodVulnerability\SRCFloodVulnerability2.gdb", workspace=r"D:\SRCFloodVulnerability\SRCFloodVulnerability2.gdb"):
        BFE()
