# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-07-30 17:00:06
"""
import arcpy

def RPL():  # Setup and RPL

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    fishnet_clip_3_ = "fishnet_clip"
    boundary = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\boundary"
    rls = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\rls"
    SRCFloodVulnerability_gdb = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb"

    # Process: Create Fishnet (Create Fishnet) 
    fishnet = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\fishnet"
    with arcpy.EnvManager(extent="1093525.89310147 497939.769396722 1264004.12891597 745335.673882142", outputCoordinateSystem="PROJCS['NAD_1983_StatePlane_Florida_North_FIPS_0903_Feet',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Lambert_Conformal_Conic'],PARAMETER['False_Easting',1968500.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-84.5],PARAMETER['Standard_Parallel_1',29.58333333333333],PARAMETER['Standard_Parallel_2',30.75],PARAMETER['Latitude_Of_Origin',29.0],UNIT['Foot_US',0.3048006096012192]]"):
        fishnet_label = arcpy.CreateFishnet_management(out_feature_class=fishnet, origin_coord="1093525.89310147 497939.769396722", y_axis_coord="1093525.89310147 497949.769396722", cell_width=1320, cell_height=1320, number_rows=None, number_columns=None, corner_coord="1264004.12891597 745335.673882142", labels="NO_LABELS", template="1097118.51091622 498733.538478479 1249866.04794022 737189.578953892", geometry_type="POLYGON")[0]

    # Process: Clip (Clip) 
    fishnet_clip = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\fishnet_clip"
    arcpy.Clip_analysis(in_features=fishnet, clip_features=boundary, out_feature_class=fishnet_clip, cluster_tolerance="")

    # Process: Feature To Point (Feature To Point) 
    fishnet_pts = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\fishnet_pts"
    arcpy.FeatureToPoint_management(in_features=fishnet_clip, out_feature_class=fishnet_pts, point_location="INSIDE")

    # Process: Generate Near Table (Generate Near Table) 
    rls_near_net = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\rls_near_net"
    arcpy.GenerateNearTable_analysis(in_features=fishnet_pts, near_features=[rls], out_table=rls_near_net, search_radius="5280 Feet", location="NO_LOCATION", angle="NO_ANGLE", closest="ALL", closest_count=0, method="PLANAR")

    # Process: Summary Statistics (Summary Statistics) 
    rls_near_fn_sum = "D:\\SRCFloodVulnerability\\SRCFloodVulnerability.gdb\\rls_near_fn_sum"
    arcpy.Statistics_analysis(in_table=rls_near_net, out_table=rls_near_fn_sum, statistics_fields=[["IN_FID", "SUM"]], case_field=["IN_FID"])

    # Process: Add Field (2) (Add Field) 
    rls_near_fn_sum_4_ = arcpy.AddField_management(in_table=rls_near_fn_sum, field_name="rls_wgt", field_type="SHORT", field_precision=None, field_scale=None, field_length=None, field_alias="rls_wgt", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) 
    rls_near_fn_sum_2_ = arcpy.CalculateField_management(in_table=rls_near_fn_sum_4_, field="rls_wgt", expression="cal_wgts(!FREQUENCY!)", expression_type="PYTHON3", code_block="def cal_wgts (pct):
    rank_val = 0
    if (pct == 1): 
            rank_val = 1
    if (pct == 2): 
            rank_val = 2
    if (pct == 3): 
            rank_val = 3
    if (pct == 4): 
            rank_val = 4
    if (pct > 4): 
            rank_val = 5
    return rank_val", field_type="TEXT")[0]

    # Process: Add Join (Add Join) 
    fishnet_clip_Layer1 = arcpy.AddJoin_management(in_layer_or_view=fishnet_clip_3_, in_field="OBJECTID", join_table=rls_near_fn_sum_2_, join_field="IN_FID", join_type="KEEP_ALL")[0]

    # Process: Feature Class to Feature Class (Feature Class to Feature Class) 
    fishnet_clip_mod1 = arcpy.FeatureClassToFeatureClass_conversion(in_features=fishnet_clip_Layer1, out_path=SRCFloodVulnerability_gdb, out_name="fishnet_clip_mod1", where_clause="", field_mapping="Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,fishnet_clip,fishnet_clip.Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,fishnet_clip,fishnet_clip.Shape_Area,-1,-1;OBJECTID \"OBJECTID\" false true false 4 Long 0 9,First,#,fishnet_clip,rls_near_fn_sum.OBJECTID,-1,-1;IN_FID \"IN_FID\" true true false 4 Long 0 0,First,#,fishnet_clip,rls_near_fn_sum.IN_FID,-1,-1;FREQUENCY \"FREQUENCY\" true true false 4 Long 0 0,First,#,fishnet_clip,rls_near_fn_sum.FREQUENCY,-1,-1;SUM_IN_FID \"SUM_IN_FID\" true true false 8 Double 0 0,First,#,fishnet_clip,rls_near_fn_sum.SUM_IN_FID,-1,-1;rls_wgt \"rls_wgt\" true true false 2 Short 0 0,First,#,fishnet_clip,rls_near_fn_sum.rls_wgt,-1,-1", config_keyword="")[0]

    # Process: Calculate Field (2) (Calculate Field) 
    fishnet_clip_mod1_2_ = arcpy.CalculateField_management(in_table=fishnet_clip_mod1, field="rls_wgt", expression="zero_out(!rls_wgt!)", expression_type="PYTHON3", code_block="def zero_out(flswgt):
    if flswgt is not None:
        return flswgt
    else:
        return 0", field_type="TEXT")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"D:\SRCFloodVulnerability\SRCFloodVulnerability2.gdb", workspace=r"D:\SRCFloodVulnerability\SRCFloodVulnerability2.gdb"):
        RPL()
